### ISSUE TITLE
Audio share doesn't work properly

### ISSUE THREAD

**Issue by AleMarigliano16** [maltejur/discord-screenaudio#28] opened 2022-07-31 09:25 UTC
Whenever I try to share audio, the audio actually shared is my mic. No matter what I choose. So the other person in call hears me twice.
I tried changing the audio input in discord settings to vmic and it shares the audio of the application but it won't get my mic anymore.
I tried both the AUR and Flatpak versions. Same issue

**Comment by MrKingMichael** [comment] 2022-07-31 11:59
A workaround: Open Pavucontrol > Recording > Change input device of bottom Chromium input process to "discord-screenaudio-virtmic".

**Comment by maltejur** [comment] 2022-07-31 13:45
Hm this is not the first time I heard of this issue, but I never had it myself. Can you share steps to reproduce this in a VM?

**Comment by maltejur** [comment] 2022-08-01 14:08
Maybe relevant issue: https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux/issues/21

Are you both using Wireplumber?

**Comment by StayBlueee** [comment] 2022-08-01 16:27
> Maybe relevant issue: [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#21](https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux/issues/21)
> 
> Are you both using Wireplumber?

I am having the same issue on X11 using Wireplumber, but either way, pipewire-media-session has been superseded by Wireplumber, and pipewire-media-session hasn't been updated in almost three months.

I am not sure how this application works, but from what I see, the application you are screen sharing feeds into virt-mic, but the audio from it doesn't get fed into anything.

My temporary solution is to unpipe the application I am trying to screen share from the virt-mic and instead pipe it directly into the chromium input for the stream (I also unpipe the stream from my microphone, so people don't hear me twice)

Image:
![image](https://user-images.githubusercontent.com/23127866/182197412-f7e79583-e617-4cc6-b077-2370659efca6.png)

**Comment by BulletBlaster** [comment] 2022-08-01 17:26
@maltejur After some testing I have concluded that a similar issue (one of the Chromium input RecordStreams being set to "Usb Audio Device Mono" and another being set to "discord-screenaudio-virtmic") happens with media-session too, hovewer switching back and forth between "Usb Audio Device Mono" and "discord-screenaudio-virtmic" in the input settings in Discord fixes it, setting both Chromium input RecordStreams to "discord-screenaudio-virtmic", while with Wireplumber they just seem to switch order for some reason.

**Comment by maltejur** [comment] 2022-08-01 17:42
Hm ok after checking I am also using wireplumber and everything works fine for me. Can one of you send me an exact setup where I can reproduce the issue?

**Comment by avidpornwatcher** [comment] 2022-08-01 19:59
I have a similar issue, but only with Wine/DXVK games. I believe this is due to XWayland, as I do not experience it in native running games that I've tested as well as streaming browser videos.

I'm going to try wine-wayland and see if I encounter similar issues, and I'll report back.

For reference, I'm using Garuda Linux with GNOME Wayland and PipeWire.

**Comment by BulletBlaster** [comment] 2022-08-01 20:09
@maltejur When you open Pavucontrol right after starting the stream are both Chromium inputs in the Recording tab set to "discord-screenaudio-virtmic"?

**Comment by maltejur** [comment] 2022-08-01 20:23
Okay the same thing now also happens to me, but only some times. Well at least I can play arround with it now and see if I can find any fix

**Comment by maltejur** [comment] 2022-08-01 20:28
Okay I have found a potential fix, just waiting at one point for all audio devices to come available. It fixed the issue for me, but it also worked flawlessly for me before so not sure if this really is the solution. Could one of the people who had this issue consistently test the changes I pushed to master?

**Comment by BulletBlaster** [comment] 2022-08-01 21:28
@maltejur I have built and tested master, sadly the top input right after starting a stream is set to "Usb Audio Device Mono":

![Screenshot_20220801_232248](https://user-images.githubusercontent.com/67292925/182248992-64e43197-6e93-412c-aef2-31cbdb8c8304.png)

Luckily now changing the input device in Discord to "Usb Audio Device Mono" and then back to "discord-screenaudio-virtmic" fixes this issue:

![Screenshot_20220801_232513](https://user-images.githubusercontent.com/67292925/182249285-ed6a18ae-43ef-482c-a634-b721f45ce700.png)

**Comment by maltejur** [comment] 2022-08-01 21:34
> sadly the top input right after starting a stream is set to "Usb Audio Device Mono"

Isnt that how you would want it to be? The top one is the microphone and the bottom one is the stream.

**Comment by AleMarigliano16** [comment] 2022-08-02 01:18
> Okay I have found a potential fix, just waiting at one point for all audio devices to come available. It fixed the issue for me, but it also worked flawlessly for me before so not sure if this really is the solution. Could one of the people who had this issue consistently test the changes I pushed to master?

It seems to work! Just tested it. Thanks.

**Comment by edisionnano** [comment] 2022-08-02 08:07
> Okay I have found a potential fix, just waiting at one point for all audio devices to come available. It fixed the issue for me, but it also worked flawlessly for me before so not sure if this really is the solution. Could one of the people who had this issue consistently test the changes I pushed to master?

Since you only have discord-screenaudio-virtmic it would probably be a better idea to poll enumerateDevices until said device shows up

**Comment by maltejur** [comment] 2022-08-02 10:42
> it would probably be a better idea to poll enumerateDevices until said device shows up

good idea, I did that now

**Comment by BulletBlaster** [comment] 2022-08-02 11:24
>Isnt that how you would want it to be? The top one is the microphone and the bottom one is the stream (at least I think this is the case here)

Really? I had no idea this project allowed proper audio share not through the microphone, will certainly need to do some more testing

**Comment by StayBlueee** [comment] 2022-08-03 07:09
Can confirm that the recent commits fixed the no sound issue on my stream.

**Comment by maltejur** [comment] 2022-08-03 07:33
Great to hear, I'll close this then

**Closed** 2022-08-03 07:34 UTC
Labels: bug
