### ISSUE TITLE
No window pops up when attempting to screenshare

### ISSUE THREAD

**Issue by StayBlueee** [maltejur/discord-screenaudio#12] opened 2022-07-26 18:27 UTC
Title says it all, no window when I press the "Screen" button on Discord.

Correction, something does pop up, but it's nothing:
![image](https://user-images.githubusercontent.com/23127866/181083865-9c5a633d-31c7-4566-bf81-cadf5bd836b5.png)

**Comment by maltejur** [comment] 2022-07-26 18:54
What "Screen" button are you talking about?

**Comment by StayBlueee** [comment] 2022-07-26 19:09
> What "Screen" button are you talking about?

The button which you use to start a screen share...

**Comment by maltejur** [comment] 2022-07-26 19:38
The button in the Discord webapp?

![image](https://user-images.githubusercontent.com/48161361/181097374-7924fc84-1757-4a7e-b8ee-f3e6d7f8453d.png)

Or the one in the popup?

**Comment by StayBlueee** [comment] 2022-07-26 20:05
> The button in the Discord webapp?
> 
> ![image](https://user-images.githubusercontent.com/48161361/181097374-7924fc84-1757-4a7e-b8ee-f3e6d7f8453d.png)
> 
> Or the one in the popup?
> 
> ![image](https://user-images.githubusercontent.com/48161361/181097468-7a4cc648-28f3-431e-b9ec-3280ddeecf4b.png)

The button in the first image. When I press that button, the Stream Dialog window that you showed in the second image doesn't show up, only a black line does.

**Comment by maltejur** [comment] 2022-07-26 20:07
That indeed shouldn't happen. I'll take a look at this issue later.

**Comment by maltejur** [comment] 2022-07-28 14:51
Can you try if the issue occurs in [this](https://github.com/maltejur/discord-screenaudio/releases/download/v1.0.0-rc.11/discord-screenaudio-v1.0.0-rc.11.flatpak) flatpak as well?

**Comment by StayBlueee** [comment] 2022-07-28 16:15
> Can you try if the issue occurs in [this](https://github.com/maltejur/discord-screenaudio/releases/download/v1.0.0-rc.11/discord-screenaudio-v1.0.0-rc.11.flatpak) flatpak as well?

As you requested I did end up giving it a try and unfortunately the Flatpak version still has the same issue.

P.S. I like the new logo ;)

**Comment by maltejur** [comment] 2022-07-28 16:38
Hm that is unfortunate. Which distro are you on?

**Comment by StayBlueee** [comment] 2022-07-28 16:42
> Hm that is unfortunate. Which distro are you on?

![image](https://user-images.githubusercontent.com/23127866/181592247-144e0c12-4d10-4140-ab0d-cfd3628726fd.png)

I should also note that I am using the proprietary Nvidia driver, which very well could be the culprit.

**Comment by maltejur** [comment] 2022-07-28 16:43
> I should also note that I am using the proprietary Nvidia driver, which very well could be the culprit.

That could very well be, yes. I am also on Arch KDE and everything works there (using open source Radeon drivers).

**Comment by maltejur** [comment] 2022-07-28 16:47
Can you try to build and test from the [resizable_dialog](https://github.com/maltejur/discord-screenaudio/tree/resizable_dialog) branch. That may fix the issue.

**Comment by StayBlueee** [comment] 2022-07-28 16:51
> Can you try to build and test from the [resizable_dialog](https://github.com/maltejur/discord-screenaudio/tree/resizable_dialog) branch? That may fix the issue.

Yep, that indeed fixed it.

**Comment by maltejur** [comment] 2022-07-28 19:46
Wait, not so fast :D

What I did was pretty much just a hack to see if the issue was with the `setFixedSize` function, we still want to make the dialog non-resizable.

I pushed new changes, can you try those again and see if it both works and the window is non-resizable?

**Comment by StayBlueee** [comment] 2022-07-29 04:33
> Wait, not so fast :D
> 
> What I did was pretty much just a hack to see if the issue was with the `setFixedSize` function, we still want to make the dialog non-resizable.
> 
> I pushed new changes, can you try those again and see if it both works and the window is non-resizable?

Haha, sorry, it's a habit of mine to close issues that I have when they are fixed so the dev doesn't have to close it themselves.

Alright, I tried it with the new changes as well and it works just as well.

**Comment by maltejur** [comment] 2022-07-29 12:31
Thanks, that means the issue is now fixed for real.

**Closed by maltejur** 2022-07-29 12:31 UTC
Labels: bug
